core/chat/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LogoutView
app_name = 'chat'

urlpatterns = [
    path('', views.landingPage, name='landing_page'),
    path('signup/', views.signup, name='signup'),
    path('login/', views.login_view, name='login'),
    path('logout/', LogoutView.as_view(next_page='/login/'), name='logout'),

    path('profile/', views.profile_detail, name='profile_detail'),
    path('profile/edit-address/', views.edit_address, name='edit_address'),
    path('profile/edit-profile/', views.edit_profile, name='edit_profile'),
    path('help/', views.help, name='help'),
    path('home/', views.home, name='home'),
    path('update-user-credentials/<uuid:id>/', views.update_user, name='update_user'),
    path('conversation/', views.conversation, name='chat_dashboard'),
    path('conversation/<uuid:chat_id>/', views.conversation, name='chat_with'),
    path('notifications/', views.buyer_notification, name='buyer_notification'),
    path("get-notifications/", views.get_notifications, name="get_notifications"),
    path("mark-notifications-read/", views.mark_notifications_read, name="mark_notifications_read"),
    path('get_unread_messages/', views.get_unread_messages_count, name='get_unread_messages'),
    path('mark_messages_read/', views.mark_messages_read, name='mark_messages_read'),
    path('about/', views.about_page, name='about'),
    path('error-page/', views.error_page, name='error'),
    path('verify/', views.verify_user, name='verify_user'),
    path('reset/new-password/', views.set_new_password, name='set_new_password'),
]

core/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('chat.urls')), 
    path('products/', include('products.urls')),
    path('manage-business/', include('manage_business.urls')),
    path('shops/', include('shops.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/products/urls.py
from django.urls import path
from . import views

app_name = 'products'

urlpatterns = [
    path('add-new-product/', views.add_new_product, name='add_new_products'),
    # path('edit-my-product?/<uuid:product_id>/', views.edit_product, name='edit_products'),
    path('add-new-business/', views.createBusiness, name='create_business'),
    path('<uuid:id>/', views.view_product, name='view_product'),
    path('wishlist/add/<uuid:product_id>/', views.add_to_wishlist, name='add_to_wishlist'),
    path('place-order/<uuid:product_id>/', views.place_order, name='place_order'),
    path('order-details/<uuid:product_id>/', views.order_details, name='order_details'),
    path('success-purchase/', views.success_purchase, name='success_purchase'),
    path('add-category/', views.add_category, name='add_category'),
    path('product_category/<uuid:category_id>/', views.show_products_category, name='show_products_category'),
]

core/shops/urls.py
from django.urls import path
from . import views

app_name = 'shops'
urlpatterns = [
    path('', views.shops_list, name='shops_list'),
    path('update-shop-informations/<uuid:pk>', views.update_shop, name='update_shop'), 
    path('view-shop/<uuid:pk>/', views.view_shop, name='view_shop'),
]

core/shops/models.py
from django.db import models

# Create your models here.

core/shops/views.py
from django.shortcuts import render, redirect, get_object_or_404
from products.models import Business
from products.forms import UpdateBusinessForm
from django.urls import reverse
from products.models import Product
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from products.models import Category
User = get_user_model()

@login_required(login_url='/login/')
def shops_list(request):
    shop = Business.objects.filter(business_name__isnull=False) | Business.objects.filter(business_name__isnull=False)
    total_shop = shop.count()
    
    context = {'shop':shop,'total_shop':total_shop}
    return render(request, 'shops/shop_list.html', context)

@login_required(login_url='/login/')
def update_shop(request, pk):
    instance = get_object_or_404(Business, pk=pk)
    if request.method == 'POST':
        form = UpdateBusinessForm(request.POST, request.FILES, instance=instance)
        if form.is_valid():
            form.save()
            return redirect(reverse('chat:profile_detail'))
    else:
        form = UpdateBusinessForm(instance=instance)
    return render(request, 'shops/update-shop.html', {'form': form})

@login_required(login_url='/login/')
def view_shop(request, pk):
    shop = get_object_or_404(Business, pk=pk)
    products = Product.objects.filter(seller=shop)
    total_products = products.count()
    user = request.user
    query = request.GET.get('q', '')
    results = Product.objects.filter(product_name__icontains=query) if query else []

    context = {
        'shop': shop,
        'product': products,
        'total_product': total_products,
        'user': user,
        'query':query,
        'results':results,
    }
    return render(request, 'shops/view-shop.html', context)

core/shops/templates/shops/shop_list.html
{% extends 'chat/base.html' %}
{% load static %}
{% block title %}
   <title>E-Kubo: Shops</title>
{% endblock title %}
<link rel="stylesheet" href="{% static 'css/slideup.css' %}">
{% block content %}
<style>
   @media (min-width: 480px) and (max-width: 768px) {
    .col {
        flex: 0 0 50%; /* Each column takes 50% width */
        max-width: 50%;
    }
}
</style>
<main>
   <!-- section -->
   <section class="mt-8 slide-up">
      <!-- container -->
      <div class="container">
         <!-- row -->
         <div class="row">
            <div class="col-12">
               <!-- heading -->
               <div class="bg-light d-flex justify-content-between ps-md-10 ps-6 rounded">
                  <div class="d-flex align-items-center">
                     <h1 class="mb-0 fw-bold" style="font-family: 'Arial', sans-serif;">Stores</h1>
                  </div>
                  <div class="py-6">
                     <!-- img -->
                     <!-- img -->
                     <img src="{% static 'images/svg-graphics/store-graphics.svg' %}" alt="" class="img-fluid" />
                  </div>
               </div>
            </div>
         </div>
      </div>
   </section>
   <!-- section -->
   <section class="mt-8 mb-lg-14 mb-8">
      <div class="container">
         <!-- row -->
         <div class="row">
            <!-- col -->
            <div class="col-12">
               <div class="mb-3">
                  <!-- text -->
                  <h6 style="font-family: 'Arial', sans-serif;">
                     We have
                     <span class="text-primary">{{total_shop}}</span>
                     vendors now
                  </h6>
               </div>
            </div>
         </div>
         <!-- <div class="row row-cols-1 row-cols-lg-4 row-cols-md-3 g-4 g-lg-4"> -->
         <div class="row row-cols-1 row-cols-md-2 row-cols-lg-4 g-4 g-lg-4">

            {% for shop in shop %}
            <div class="col">
               <!-- card -->
               <div class="card p-6 card-product">
                  <div style="display: flex; justify-content: center; align-items: center;">
                     <img style="height: 70px; width: 90px; border-radius: 10px; box-shadow: 1px 1px 2px rgb(85, 85, 85);" src="{{ shop.business_image_url }}" alt="" />
                  </div>
                 
                  <div class="mt-4" style="font-family: 'Arial', sans-serif;">
                     <!-- content -->
                     <h2 class="mb-1 h5"><a href="{% url 'shops:view_shop' shop.id %}" class="text-inherit">{{ shop.business_name }}</a></h2>
                     <div class="small text-muted">
 
                        <p class="me-2">{{shop.business_description}}</p>
                        <p>message owner: <a style="color: rgb(62, 62, 205);" href="{% url 'chat:chat_with' shop.user.id %}">message</a>
                        </p> 
                     </div>
                     <div class="py-3" style="font-family: 'Arial', sans-serif;">
                        <ul class="list-unstyled mb-0 small">
                           <p class="mb-0"><b>Shipping:</b></p>
                           <li>- Delivery</li>
                           <li>- Pickup</li>
                        </ul>
                     </div>
                     <div>
                        <!-- badge -->
                        <div class="badge text-bg-light border">available products: {{ shop.products.count }}</div>
                     </div>
                  </div>
               </div>
            </div>
            {% endfor %}
         </div>
      </div>
   </section>
</main>
<script src="{% static 'js/slideup.js' %}"></script>
{% endblock %}

core/shops/templates/shops/update-shop.html
{% load static %}
{% block title %}
   <title>E-Kubo: Update shop info</title>
{% endblock title %}
<link rel="stylesheet" href="{% static 'css/slideup.css' %}">
<form class="slide-up" method="post" enctype="multipart/form-data" style="font-family: 'Arial', sans-serif;">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" style="font-family: 'Arial', sans-serif;">Update</button>
</form>
<script src="{% static 'js/slideup.js' %}"></script>

core/shops/templates/shops/view-shop.html
{% extends 'chat/base.html' %}
{% load static %}
{% block content %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
<link rel="stylesheet" href="{% static 'css/slideup.css' %}">
<!-- section-->
      <main>
         <!-- section -->
         <section class="mb-lg-14 mb-8 mt-8 slide-up">
            <div class="container">
               <!-- row -->
               <div class="row">
                  <div class="col-12 col-lg-3 col-md-4 mb-4 mb-md-0">
                     <div class="d-flex flex-column">
                        <div>
                           <!-- img -->
                           <!-- img -->
                           <img src="{{shop.business_image_url}}" alt="" class="rounded-circle icon-shape icon-xxl" />
                        </div>
                        <!-- heading -->
                        <div class="mt-4" style="font-family: 'Arial', sans-serif;">
                           <h1 class="mb-1 h4">{{shop.business_name}}</h1>
                           <div class="small text-muted">
                              <span>{{shop.business_description}}</span> <br>
                              <span>Contact #: {{ shop.business_contact_number }}</span>
                              <p>Address: {{ shop.business_address }}</p>
                           </div>
                           <div>
                              <span>
                                 <a href="{% url 'chat:chat_with' shop.user.id %}"><p>Message seller</p></a>
                              </span>
                           </div>
                        </div>
                     </div>
                     <hr />
                     <!-- nav -->
                     <ul class="nav flex-column nav-pills nav-pills-dark">
                        <!-- nav item -->
                        <li class="nav-item" style="font-family: 'Arial', sans-serif;">
                           <a class="nav-link active" aria-current="page" href="#">
                              <i class="feather-icon icon-shopping-bag me-2"></i>
                              Products available
                           </a>
                        </li>
                        <ul class="nav flex-column nav-links">
                           <!-- nav item -->
                           <li class="nav-item" style="font-family: 'Arial', sans-serif;">
                              <a href="#!" class="nav-link">Products</a>
                           </li>
                           <!-- nav item -->
                           {% for product in product %}
                           <li class="nav-item" style="font-family: 'Arial', sans-serif;">
                              <a href="" class="nav-link">{{ product.product_name }}</a>
                           </li>
                           {% endfor %}
                        </ul>
                     </ul>
                     <hr />
                  </div>
                  <div class="col-12 col-lg-9 col-md-8">
                     <div class="mb-8 bg-light d-lg-flex justify-content-lg-between rounded">
                        <div class="align-self-center p-8">
                           <div class="mb-3" style="font-family: 'Arial', sans-serif;">
                              <h5 class="mb-0 fw-bold">{{shop.business_name}}</h5>
                              <p class="mb-0 text-muted">{{shop.business_description}}</p>
                           </div>
                        </div>
                        <div class="py-4">
                           <!-- img -->
                           <img src="{% static 'images/svg-graphics/store-graphics.svg' %}" alt="" class="img-fluid" />
                        </div>
                     </div>

                     <div class="d-md-flex justify-content-between mb-3 align-items-center">
                        <div style="font-family: 'Arial', sans-serif;">
                           <p class="mb-3 mb-md-0">{{total_product}} Products found</p>
                        </div>
                     </div>
                     {% if query %}
                     <div class="row g-4 row-cols-lg-5 row-cols-2 row-cols-md-3">
                        {% for result in results %}
                        <div class="col">
                           <div class="card card-product">
                              <div class="card-body">
                                 <div class="text-center position-relative">
                                    <div class="position-absolute top-0 start-0" style="font-family: 'Arial', sans-serif;">
                                       {% if result.product_stock >= 1 %}
                                          <small class="text-white" style="background-color: #00b200; border-radius: 5px; padding: 2px;">available</small>
                                       {% else %}
                                          <small>unavailable</small>
                                       {% endif %}
                                       <form style="margin-left: 0px;" action="{% url 'products:add_to_wishlist' result.id %}" method="POST">
                                          {% csrf_token %}
                                          <button style="border-radius: 20px; margin: 0; border-color: #00b200;">
                                             <i style="font-size: 15px;" class="bi bi-heart"></i> 
                                          </button>
                                       </form>
                                    </div>
                                    <a href="{% url 'products:view_product' result.id %}"><img width="200px" height="350px" src="{{result.product_image_url}}" alt="Grocery Ecommerce Template" class="mb-3 img-fluid" /></a>
                                 </div>
                                 <div class="text-small mb-1" style="font-family: 'Arial', sans-serif;">
                                    <a href="#!" class="text-decoration-none text-muted"><small>category: {{result.product_category}}</small></a>
                                 </div>
                                 <h2 style="font-family: 'Arial', sans-serif;" class="fs-6"><a href="pages/shop-single.html" class="text-inherit text-decoration-none">{{result.product_name}}</a></h2>
                                 <div class="d-flex justify-content-between align-items-center mt-3">
                                    <div style="font-family: 'Arial', sans-serif;" >
                                       <span class="text-dark">₱{{result.product_price}} per {{result.product_measurement}}</span>
                                    </div>
                                    <div style="font-family: 'Arial', sans-serif;">
                                       <form action="{% url 'products:order_details' result.id %}" method="POST">
                                          {% csrf_token %}
                                          <button style="padding-left: 10px; padding-right: 10px; background-color: #00b200;;" type="submit" class="btn text-white"><b>Buy</b></button>
                                       </form>
                                    </div>
                                 </div>
                              </div>
                           </div>
                           </a>
                        </div>
                        {% endfor %}
                     </div>
                     {% else %}
                     <!-- row -->
                     <div class="row g-4 row-cols-lg-5 row-cols-2 row-cols-md-3">
                        {% for products in product %}
                        <div class="col">
                           <div class="card card-product">
                              <div class="card-body">
                                 <div class="text-center position-relative">
                                    <div class="position-absolute top-0 start-0" style="font-family: 'Arial', sans-serif;">
                                       {% if products.product_stock >= 1 %}
                                          <small class="text-white" style="background-color: #00b200; border-radius: 5px; padding: 2px;">available</small>
                                       {% else %}
                                          <small>unavailable</small>
                                       {% endif %}
                                       <form style="margin-left: 0px;" action="{% url 'products:add_to_wishlist' products.id %}" method="POST">
                                          {% csrf_token %}
                                          <button style="border-radius: 20px; margin: 0; border-color: #00b200;">
                                             <i style="font-size: 15px;" class="bi bi-heart"></i> 
                                          </button>
                                       </form>
                                    </div>
                                    <a href="{% url 'products:view_product' products.id %}"><img width="200px" height="350px" src="{{products.product_image_url}}" alt="Grocery Ecommerce Template" class="mb-3 img-fluid" /></a>
                                 </div>
                                 <div class="text-small mb-1" style="font-family: 'Arial', sans-serif;">
                                    <a href="#!" class="text-decoration-none text-muted"><small>category: {{products.product_category}}</small></a>
                                 </div>
                                 <h2 class="fs-6" style="font-family: 'Arial', sans-serif;"><a href="pages/shop-single.html" class="text-inherit text-decoration-none">{{products.product_name}}</a></h2>
                                 <div class="d-flex justify-content-between align-items-center mt-3" style="font-family: 'Arial', sans-serif;">
                                    <div>
                                       <span class="text-dark">₱{{products.product_price}} per {{products.product_measurement}}</span>
                                    </div>
                                    <div>
                                       <form action="{% url 'products:order_details' products.id %}" method="POST">
                                          {% csrf_token %}
                                          <button style="padding-left: 10px; padding-right: 10px; background-color: #00b200;;" type="submit" class="btn text-white"><b>Buy</b></button>
                                       </form>
                                    </div>
                                 </div>
                              </div>
                           </div>
                           </a>
                        </div>
                        {% endfor %}
                     </div>
                     {% endif %}
                  </div>
               </div>
            </div>
         </section>
      </main>
<script src="{% static 'js/slideup.js' %}"></script>
{% endblock %}