core/chat/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LogoutView
app_name = 'chat'

urlpatterns = [
    path('', views.landingPage, name='landing_page'),
    path('signup/', views.signup, name='signup'),
    path('login/', views.login_view, name='login'),
    path('logout/', LogoutView.as_view(next_page='/login/'), name='logout'),

    path('profile/', views.profile_detail, name='profile_detail'),
    path('profile/edit-address/', views.edit_address, name='edit_address'),
    path('profile/edit-profile/', views.edit_profile, name='edit_profile'),
    path('help/', views.help, name='help'),
    path('home/', views.home, name='home'),
    path('update-user-credentials/<uuid:id>/', views.update_user, name='update_user'),
    path('conversation/', views.conversation, name='chat_dashboard'),
    path('conversation/<uuid:chat_id>/', views.conversation, name='chat_with'),
    path('notifications/', views.buyer_notification, name='buyer_notification'),
    path("get-notifications/", views.get_notifications, name="get_notifications"),
    path("mark-notifications-read/", views.mark_notifications_read, name="mark_notifications_read"),
    path('get_unread_messages/', views.get_unread_messages_count, name='get_unread_messages'),
    path('mark_messages_read/', views.mark_messages_read, name='mark_messages_read'),
    path('about/', views.about_page, name='about'),
    path('error-page/', views.error_page, name='error'),
    path('verify/', views.verify_user, name='verify_user'),
    path('reset/new-password/', views.set_new_password, name='set_new_password'),
]

core/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('chat.urls')), 
    path('products/', include('products.urls')),
    path('manage-business/', include('manage_business.urls')),
    path('shops/', include('shops.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/manage_business/urls.py
from django.urls import path
from . import views

app_name = 'manage_business'

urlpatterns = [
    path('seller/dashboard/', views.seller_dashboard, name='home'),
    path('order/accept/<int:order_id>/', views.accept_order, name='accept_order'),
    path('order/reject/<int:order_id>/', views.reject_order, name='reject_order'),
    path('delete-product/<uuid:product_id>/', views.delete_product, name='delete_product'),
]

core/shops/urls.py
from django.urls import path
from . import views

app_name = 'shops'
urlpatterns = [
    path('', views.shops_list, name='shops_list'),
    path('update-shop-informations/<uuid:pk>', views.update_shop, name='update_shop'), 
    path('view-shop/<uuid:pk>/', views.view_shop, name='view_shop'),
]

core/chat/models.py
from arrow import now
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.contrib.auth.models import AbstractUser, Group, Permission
import uuid
from django.db import models
from django.conf import settings

class CustomUser(AbstractUser):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    email = models.EmailField(unique=True)
    phone = models.BigIntegerField(null=True, blank=True)
    is_seller = models.CharField(max_length=45, choices=[('yes', 'yes'), ('no', 'no')])
    failed_attempts = models.IntegerField(default=0)
    last_failed_attempt = models.DateTimeField(null=True, blank=True)
    groups = models.ManyToManyField(
        Group,
        related_name='customuser_set',  # specify a custom related_name
        blank=True
    )
    user_permissions = models.ManyToManyField(
        Permission,
        related_name='customuser_permissions',  # specify a custom related_name
        blank=True
    )


class Message(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    sender = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='sent_messages', on_delete=models.CASCADE)
    receiver = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='received_messages', on_delete=models.CASCADE)
    content = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)
    is_read = models.BooleanField(max_length=45, default=False)

    def __str__(self):
        return f"{self.content}"

class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    profile = models.ImageField(upload_to='user_profiles', default='default.png')
    province = models.CharField(max_length=100, null=True, blank=True)
    municipality = models.CharField(max_length=100, null=True, blank=True)
    street = models.CharField(max_length=200,  null=True, blank=True)
    postal_code = models.CharField(max_length=20,  null=True, blank=True)
    last_seen = models.DateTimeField(null=True, blank=True)

    def is_online(self):
        """ Check if the user was active within the last 1 second """
        if self.last_seen:
            return (now() - self.last_seen).total_seconds() < 300  
            # return (now() - self.last_seen).total_seconds() < 1
        
    def __str__(self):
        return f"{self.user.username} - {self.street if self.street else 'No Address'}"
    
    def profile_image_url(self):
        try: 
            url = self.profile.url
        except:
            url = ''

@receiver(post_save, sender=settings.AUTH_USER_MODEL)
def create_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=settings.AUTH_USER_MODEL)
def save_profile(sender, instance, **kwargs):
    instance.profile.save()

core/chat/forms.py
from django import forms
from .models import     Profile
from django.contrib.auth import get_user_model

User = get_user_model()

class EditProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields  = ['profile']

class DeliveryAddressForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['province', 'municipality', 'street', 'postal_code']

class UpdateUser(forms.ModelForm):
    phone = forms.CharField(
        max_length=15,
        required=True,
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter phone number'})
    )

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'phone']
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter username'}),
        }
class VerifyUserForm(forms.Form):
    email = forms.EmailField()
    password = forms.CharField(widget=forms.PasswordInput)


# forms.py (add below the previous form)
class SetNewPasswordForm(forms.Form):
    new_password = forms.CharField(widget=forms.PasswordInput)
    confirm_password = forms.CharField(widget=forms.PasswordInput)

    def clean(self):
        cleaned_data = super().clean()
        new = cleaned_data.get("new_password")
        confirm = cleaned_data.get("confirm_password")
        if new != confirm:
            raise forms.ValidationError("Passwords do not match")
        return cleaned_data

core/chat/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Message, Profile
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from random import choice
from .forms import DeliveryAddressForm, EditProfileForm, UpdateUser
from django.contrib.auth.models import auth
from django.urls import reverse
from products.models import Product,Notification, Business, Wishlist
from django.conf import settings
from django.contrib.auth import get_user_model
from django.db.models import Q
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from products.models import Order
from products.models import Category, Product, Business, Wishlist, Review
import random
from django.db.models import Max, Q
import requests
from .capture_image import capture_image
from .email_utils import send_email_with_image
from django.utils.timezone import now
from .forms import VerifyUserForm, SetNewPasswordForm
from uuid import UUID
User = get_user_model()


def signup(request):
    if request.method == 'POST':
        first_name = request.POST.get('first_name')
        last_name = request.POST.get('last_name')
        email = request.POST.get('email')
        password = request.POST.get('password')
        confirm_password = request.POST.get('confirm_password')
        recaptcha_response = request.POST.get("g-recaptcha-response")

        data = {
            "secret": "6LfndgYrAAAAAKfMxiRbV0BI0pqvEHHkqyWRYRKO",
            "response": recaptcha_response
        }
        google_url = "https://www.google.com/recaptcha/api/siteverify"
        response = requests.post(google_url, data=data)
        result = response.json()

        if not result.get("success"):
            messages.error(request, "reCAPTCHA verification failed. Please try again.")
            return redirect(reverse("chat:signup"))
        
        if password != confirm_password:
            messages.error(request, "Passwords do not match.")
            return redirect(reverse('chat:signup'))

        if User.objects.filter(email=email).exists():
            messages.error(request, "Email already exists.")
            return redirect(reverse('chat:signup'))
        
        if len(password) < 8:
            messages.info(request, "Password must contain at least 8 characters.")
            return redirect(reverse('chat:signup'))
        
        user = User.objects.create_user(
            username=email,
            first_name=first_name,
            last_name=last_name,
            email=email,
            password=password,
        )
        user.save()
        messages.success(request, "Account created successfully. Please log in.")
        return redirect(reverse('chat:login'))
    
    return render(request, 'chat/temp-signup.html')

FAILED_ATTEMPTS = {}
def login_view(request):
    if request.method == 'POST':
        email = request.POST.get('email')
        password = request.POST.get('password')
        user = authenticate(request, username=email, password=password)
        
        if user is not None:
            login(request, user)
            user.failed_attempts = 1
            user.last_failed_attempt = None
            user.save()

            if Business.objects.filter(user=user).exists():
                messages.success(request, 'Welcome back! ' + str(user.first_name))
                return redirect(reverse('manage_business:home'))
            else:
                messages.success(request, 'Welcome back! ' + str(user.first_name))
                return redirect(reverse('chat:home'))
        else:
            try:
                user = User.objects.get(email=email)
                user.failed_attempts += 1
                user.last_failed_attempt = now()

                if user.failed_attempts >=3 :
                    image_path = capture_image()
                    send_email_with_image(user, image_path)
                    user.failed_attempts = 0 
                    messages.warning(request, "Too many failed attempts.")
                user.save()
            except User.DoesNotExist:
                messages.error(request, "Invalid email or password.")
                return redirect(reverse('chat:login'))
            messages.error(request, "Invalid email or password.")
            return redirect(reverse('chat:login'))
    return render(request, 'chat/temp_login.html')

def landingPage(request):
    products = Product.objects.order_by('?')
    categories = Category.objects.order_by('?')
    query = request.GET.get('q', '')
    results = Product.objects.filter(product_name__icontains=query) if query else []
    new_arrivals = Product.objects.all().order_by("-created_at")[:4]
    
    context = {
        'query':query,
        'products':products,
        'results':results,
        'categories':categories,
        'new_arrivals':new_arrivals
    }
    return render(request, 'chat/landing_page.html', context)

@login_required(login_url='/login/')
def home(request):
    wishlist_items = Wishlist.objects.filter(user=request.user).aggregate()
    products = Product.objects.all()
    users_with_business = User.objects.filter(business__isnull=False)
    unread_notifications = Notification.objects.filter(user=request.user, is_read=False).count()
    categories = Category.objects.all()
    query = request.GET.get('q', '')
    reviews = Review.objects.all().order_by('-created_at')[:3]
    results = Product.objects.filter(product_name__icontains=query) if query else []
    new_arrivals = Product.objects.all().order_by("-created_at")[:4]

    purchased_categories = Product.objects.filter(
        order__buyer=request.user,
        order__status__in=["Accepted", "Pending"]
    ).values_list('product_category', flat=True).distinct()

    # if purchased_categories:
    #     recommended_products = Product.objects.filter(
    #         product_category__in=purchased_categories
    #     ).exclude(order__buyer=request.user).order_by('?')
    # else:
    #     recommended_products = Product.objects.all().order_by("?")[:10]
    if purchased_categories:
        recommended_products = Product.objects.filter(
            product_category__in=purchased_categories
        ).exclude(order__buyer=request.user).order_by('?')
    else:
        recommended_products = Product.objects.none()


    context = {
        'query': query,
        'products': products,
        'has_business': users_with_business,
        'results': results,
        'unread_notifications': unread_notifications,
        'categories': categories,
        'new_arrivals': new_arrivals,
        'reviews': reviews,
        'recommended_products': recommended_products
    }
    return render(request, 'chat/home.html', context)

@login_required(login_url='/login/')
def error_page(request):
    return render(request, 'chat/404error.html')

@login_required(login_url='/login/')
def about_page(request):
    return render(request, 'chat/about.html')

@login_required(login_url='/login/')
def conversation(request, chat_id=None):
    users = User.objects.filter(
        Q(received_messages__sender=request.user) | Q(sent_messages__receiver=request.user)
    ).distinct()
    users = users.annotate(
        latest_message_time=Max(
            'received_messages__timestamp',
            filter=Q(received_messages__sender=request.user) | Q(sent_messages__receiver=request.user)
        )
    ).order_by('-latest_message_time')

    search_query = request.GET.get('search_user')
    if search_query:
        users = users.filter(first_name__icontains=search_query)

    current_user = None
    if chat_id:
        current_user = get_object_or_404(User, id=chat_id)
    elif users.exists():
        current_user = random.choice(users)

    messages = []
    last_messages = {}

    if current_user:
        if request.method == 'POST':
            content = request.POST.get('content')
            if content:
                Message.objects.create(sender=request.user, receiver=current_user, content=content)

                if not current_user.profile.is_online():
                    auto_message = "Hello! I'm currently offline. I'll get back to you soon."
                    Message.objects.create(sender=current_user, receiver=request.user, content=auto_message)

        messages = Message.objects.filter(
            Q(sender=request.user, receiver=current_user) | Q(sender=current_user, receiver=request.user)
        ).order_by('timestamp')

    for user in users:
        last_message = Message.objects.filter(
            Q(sender=request.user, receiver=user) | Q(sender=user, receiver=request.user)
        ).order_by('-timestamp').first()
        last_messages[user.id] = last_message

    context = {
        'users': users,
        'user_profile': users,
        'current_user': current_user,
        'messages': messages,
        'last_message': last_messages,
    }

    return render(request, 'chat/conversation.html', context)

@login_required(login_url='/login/')
def get_unread_messages_count(request):
    unread_count = Message.objects.filter(receiver=request.user, is_read=False).count()
    return JsonResponse({"count": unread_count})

@login_required(login_url='/login/')
def mark_messages_read(request):
    Message.objects.filter(receiver=request.user, is_read=False).update(is_read=True)
    return JsonResponse({"status": "success"})

@login_required(login_url='/login/')
def edit_address(request):
    profile, created = Profile.objects.get_or_create(user=request.user)
    form = DeliveryAddressForm()
    if request.method == 'POST':
        form = DeliveryAddressForm(request.POST, request.FILES, instance=profile)
        if form.is_valid():
            form.save()
            return redirect(reverse('chat:profile_detail'))
    else:
        form = DeliveryAddressForm(instance=profile)

core/chat/templates/chat/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    {% include 'chat/head.html' %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    {% block title %}
    {% endblock title %}
</head>
<body>
    
    {% include 'chat/navbar.html' %}

    {% block content %}

    
    {% endblock %}

    {% block footer %}
        {% include 'chat/footer.html' %}
    {% endblock %}
    <!-- Bootstrap 5 CSS -->

<!-- Bootstrap 5 JS (Requires Popper.js) -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>

</body>
</html>

core/chat/templates/chat/orig-navbar.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Refreshify Navbar</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" rel="stylesheet">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="../assets/libs/bootstrap-icons/font/bootstrap-icons.min.css" rel="stylesheet" />
    <link href="../assets/libs/feather-webfont/dist/feather-icons.css" rel="stylesheet" />
    <link href="../assets/libs/simplebar/dist/simplebar.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="../assets/css/theme.min.css" />
    <style>
        .sidebars {
        position: fixed;
        top: 0;
        right: -300px;
        width: 300px;
        height: 100%;
        background: #fff;
        box-shadow: -2px 0 5px rgba(0, 0, 0, 0.2);
        transition: right 0.3s ease-in-out;
        padding: 20px;
        z-index: 1001;
    }
    .sidebars.active {
        right: 0;
    }
    .overlay {
        position: fixed;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        background: rgba(0, 0, 0, 0.5);
        opacity: 0;
        visibility: hidden;
        transition: opacity 0.3s ease-in-out;
        z-index: 1000;
    }
    .overlay.active {
        opacity: 1;
        visibility: visible;
    }
    .sidebars ul {
        padding: 0;
        list-style: none;
    } 
    .sidebars ul li {
        margin: 15px 0;
    }
    .sidebars ul li a {
        text-decoration: none;
        color: #141414;
        font-size: 18px;
        display: flex;
        align-items: center; 
    }
    .sidebars ul li a i {
        margin-right: 10px;  
        font-size: 20px; 
    } 
    
    /* Change background color on hover */
    .dropdown-menu .dropdown-item:hover {
        background-color: rgb(31, 151, 69) !important;
        color: white !important;
    }

    </style>
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
</head>  
<body>
    <nav class="navbar navbar-expand-lg px-3 shadow-sm" style="background-color: white; position: sticky; top: 0; z-index: 1030;">
        <div class="container-fluid">
            <!-- Logo -->
            {% if request.user.business %}
                <a class="navbar-brand d-flex align-items-center" href="{% url 'manage_business:home' %}">
                    <img src="../../../static/icons/logo1.png" alt="Refreshify Logo" width="80" height="70">
                    <h3 class="ms-2 mb-0 fw-bold text-dark" style="font-family: 'Itim', cursive;">E-Kubo</h3>
                </a>
            {% else %}
                <a class="navbar-brand d-flex align-items-center" href="{% url 'chat:home' %}">
                    <img src="../../../static/icons/logo1.png" alt="Refreshify Logo" width="80" height="70">
                    <h3 class="ms-2 mb-0 fw-bold text-dark" style="font-family: 'Itim', cursive;">E-Kubo</h3>
                </a>
            {% endif %}

            <!-- Toggle Button for Mobile -->
            <button class="navbar-toggler" type="button" id="navbar-toggler">
                <span class="navbar-toggler-icon"></span>
            </button>
    
            <!-- Navbar Items -->
            <div class="collapse navbar-collapse" id="navbarNav">
                {% if user.is_authenticated %}
                <ul class="navbar-nav ms-auto align-items-center">
                    {% if request.user.business %}
                    {% else %}
                    <li class="nav-item dropdown" style="font-family: 'Arial', sans-serif;">
                        <a class="nav-link" href="{% url 'shops:shops_list' %}"  aria-expanded="false">
                            Stores
                        </a>
                    </li>  
                    <li><a class="dropdown-item text-secondary mr-2 ml-2" href="{% url 'chat:about' %}">About us</a></li>
                    <!-- Pages Dropdown -->
                    <!-- <li class="nav-item dropdown" style="font-family: 'Arial', sans-serif;"> 
                        <a class="nav-link dropdown-toggle" href="#" id="pagesDropdown" role="button" data-bs-toggle="dropdown">Pages</a>
                        
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="#">Contact us</a></li>
                            <li><a class="dropdown-item" href="{% url 'chat:about' %}">About us</a></li>
                        </ul>
                    </li> -->
                    {% endif %}

                    <!-- Notification -->
                    <li class="nav-item">
                        <a class="nav-link position-relative" href="{% url 'chat:buyer_notification' %}" id="notification-link">
                            <img src="../../../static/icons/not.png" width="25" height="25" alt="Notifications">
                            <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger" id="notification-count">0</span>
                        </a>
                    </li>
    
                    <!-- Messages -->
                    <li class="nav-item">
                        <a class="nav-link position-relative" href="{% url 'chat:chat_dashboard' %}" id="message-link">
                            <i class="fab fa-facebook-messenger fs-5"></i>
                            <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger" id="message-count">0</span>
                        </a>
                    </li>
    
                    <!-- Profile -->
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'chat:profile_detail' %}">
                            <i class="bi bi-person-circle fs-4"></i>
                        </a>
                    </li>
                </ul>
                    {% if request.user.business %}
                    {% else %}
                        <form method="GET" action="{% url 'chat:home' %}" class="d-flex ms-3">
                            <input class="form-control" type="search" name="q" placeholder="Search for products..." aria-label="Search"
                                style="height: 45px;">
                            <button class="btn btn-success" type="submit" style="height: 45px; font-family: Arial, sans-serif;">Search</button>
                        </form>
                    {% endif %}
                {% else %}
                <div class="d-flex w-100 justify-content-between align-items-center" style="font-family: 'Arial', sans-serif;"> 
                    <form method="GET" action="{% url 'chat:home' %}" class="d-flex ms-3">
                        <input class="form-control" type="search" name="q" placeholder="Search for products..." aria-label="Search"
                            style="height: 45px; width: 500px;">
                        <button class="btn btn-success" type="submit" style="height: 45px;">Search</button>
                    </form>
                    <div class="ms-auto">
                        <a href="{% url 'chat:login' %}">
                            <button style="border-radius: 20px;" type="submit">Sign in</button>
                        </a>
                    </div>
                </div>
                
                {% endif %}
            </div>
        </div>
    </nav>
    

    <script>
        document.addEventListener("DOMContentLoaded", function () {
            const navbarToggler = document.getElementById("navbar-toggler");
            const navbarNav = document.getElementById("navbarNav");

            navbarToggler.addEventListener("click", function () {
                navbarNav.classList.toggle("show");
            });

            // Close navbar when clicking outside
            document.addEventListener("click", function (event) {
                if (!navbarNav.contains(event.target) && !navbarToggler.contains(event.target)) {
                    navbarNav.classList.remove("show");
                }
            });
        });

        document.addEventListener("DOMContentLoaded", function () {
            const sidebar = document.getElementById("sidebar");
            const overlay = document.getElementById("overlay");
            const menuToggle = document.getElementById("menu-toggle");
            menuToggle.addEventListener("click", function () {
                sidebar.classList.add("active");
                overlay.classList.add("active");
            });
            overlay.addEventListener("click", function () {
                sidebar.classList.remove("active");
                overlay.classList.remove("active");
            });
        });


        document.addEventListener("DOMContentLoaded", function () {
            const notificationCountElement = document.getElementById("notification-count");
            const notificationLink = document.getElementById("notification-link");

            function fetchNotifications() {
                fetch("{% url 'chat:get_notifications' %}") 
                    .then(response => response.json())
                    .then(data => {
                        if (data.count > 0) {
                            notificationCountElement.textContent = data.count;
                        } else {
                            notificationCountElement.textContent = "";
                        }
                    });
            }

            notificationLink.addEventListener("click", function () {
                fetch("{% url 'chat:mark_notifications_read' %}", {
                    method: "POST",
                    headers: {
                        "X-CSRFToken": getCSRFToken(),
                        "X-Requested-With": "XMLHttpRequest",
                    },
                }).then(() => {
                    notificationCountElement.textContent = "";
                });
            });

            function getCSRFToken() {
                    return document.querySelector("[name=csrfmiddlewaretoken]").value;
                }

                fetchNotifications();  // Load notifications on page load
                setInterval(fetchNotifications, 10000);  // Fetch every 10 seconds
            });




            //for tracking if there is new message in messenger
            document.addEventListener("DOMContentLoaded", function () {
        const messageCountElement = document.getElementById("message-count");
        const messageLink = document.getElementById("message-link");

        function fetchUnreadMessages() {
            fetch("{% url 'chat:get_unread_messages' %}") // Update with your actual URL name
                .then(response => response.json())
                .then(data => {
                    if (data.count > 0) {
                        messageCountElement.textContent = data.count;
                    } else {
                        messageCountElement.textContent = "";
                    }
                });
        }

        messageLink.addEventListener("click", function () {
            fetch("{% url 'chat:mark_messages_read' %}", {
                method: "POST",
                headers: {
                    "X-CSRFToken": getCSRFToken(),
                    "X-Requested-With": "XMLHttpRequest",
                },
            }).then(() => {
                messageCountElement.textContent = "";
            });
        });

        function getCSRFToken() {
            return document.querySelector("[name=csrfmiddlewaretoken]").value;
        }

        fetchUnreadMessages();  // Load unread messages count on page load
        setInterval(fetchUnreadMessages, 10000);  // Fetch every 10 seconds
    });

    </script>
    <!-- Bootstrap 5 CSS -->
    <!-- Bootstrap 5 JS (Requires Popper.js) -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
    <script src="../assets/libs/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="../assets/libs/simplebar/dist/simplebar.min.js"></script>
    <script src="../assets/js/vendors/jquery.min.js"></script>
    <script src="../assets/libs/slick-carousel/slick/slick.min.js"></script>
    <script src="../assets/js/vendors/slick-slider.js"></script>
    <script src="../assets/libs/tiny-slider/dist/min/tiny-slider.js"></script>
    <script src="../assets/js/vendors/tns-slider.js"></script>
</body>
</html>

core/chat/templates/chat/vendor_base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    {% include 'chat/head.html' %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="icon" type="image/png" href="{% static 'icons/ekubo_icon.png' %}">
</head>
<body>
    
    {% include 'chat/seller_navbar.html' %}

    {% block content %}

    
    {% endblock %}
    <!-- Bootstrap 5 CSS -->

<!-- Bootstrap 5 JS (Requires Popper.js) -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>

</body>
</html>